ldm:
  base_lr: 0.000025
  params:
    spatial_dims: 2
    in_channels: 3
    out_channels: 3
    num_res_blocks: 2
    num_channels: [256, 512, 768]
    attention_levels: [False, True, True]
    with_conditioning: True
    cross_attention_dim: 1024
    num_head_channels: [0, 512, 768]
  scheduler:
    # https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/scheduler/scheduler_config.json
    schedule: "scaled_linear_beta"
    num_train_timesteps: 1000 # TODO: Ablation how results turn out for range 100-1000
    beta_start: 0.0015
    beta_end: 0.0205
    prediction_type: "v_prediction"

# Adding stage 1 info here if state dict is loaded from stage 1 - then we need to init AEKL first (rather than loading it directly with mlflow)
stage1:
  base_lr: 0.00001
  disc_lr: 0.00005
  perceptual_weight: 0.002
  adv_weight: 0.005
  kl_weight: 0.00000001
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels: [128, 256, 256, 512]
    latent_channels: 3
    num_res_blocks: 2
    attention_levels: [False, False, False, False]
    with_encoder_nonlocal_attn: False
    with_decoder_nonlocal_attn: False

discriminator:
  params:
    spatial_dims: 2
    num_channels: 128
    num_layers_d: 3
    in_channels: 1
    out_channels: 1

perceptual_network:
  params:
    spatial_dims: 2
    network_type: "squeeze"
